name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for pre-built artifacts
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: check_dist
        run: test -d test/dist && echo "dist_exists=true" >> $GITHUB_OUTPUT || echo "dist_exists=false" >> $GITHUB_OUTPUT

      - name: Setup Node.js (only if dist not found)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.check_dist.outputs.dist_exists == 'false'
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: 'test/package-lock.json'

      - name: Install dependencies (only if dist not found)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.check_dist.outputs.dist_exists == 'false'
        working-directory: test
        run: npm ci

      - name: Build project (only if dist not found)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.check_dist.outputs.dist_exists == 'false'
        working-directory: test
        run: npm run build

      - name: Setup Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v4
        with:
          enablement: true

      - name: Upload artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'test/dist'

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v2
